### ISSUE TITLE
Add ignore messages that the bot sends

### ISSUE THREAD

**Issue by DareFox** [Team-Nope/Botly#1]
Make it like optional check mark, which by default is turned on

![Code_j6x0HNewQV](https://user-images.githubusercontent.com/47672780/85964161-3eb38300-b9c1-11ea-8005-4b83e1d947ec.png)

**Comment by FirstPotatoMan** [comment]
I added the "Me" block for this specific reason. You should just be able to do
![screencapture-botly-56339-web-app-1593405041717](https://user-images.githubusercontent.com/65626203/85973133-a7313e80-b986-11ea-8b9c-fe6f35316733.png)
